### ISSUE TITLE
integrate ESLint and Prettier

### ISSUE THREAD

**Issue by SergiuB** [code4romania/czl-web#5]
Summed up pretty good [here](https://medium.com/@eliotjunior/prettier-eslint-facebook-code-quality-the-auto-magical-react-styling-tutorial-19481acb10dd)

**Comment by aaannddrraaa** [comment]
Done [here](https://github.com/code4romania/czl-web/commit/e19349e1f8b725baa9eb32350b814df8c613745e).

**Comment by SergiuB** [comment]
Great stuff, it should make contributions and reviews a lot easier. 👌
